// Curated groups of page-text keys shown in the "Page Content" tab, mirroring
// the section comments in src/translations.js. Pizza names/descriptions and
// snack/dessert names/descriptions have their own dedicated editors (Pizzas
// and Extras tabs) so they aren't duplicated here.
const LONG = true;

export const CONTENT_SECTIONS = [
  {
    id: "navbar",
    title: "Navbar & Menu Labels",
    fields: [
      { key: "home", label: "Nav: Home" },
      { key: "menu", label: "Nav: Menu" },
      { key: "extras", label: "Nav: Sides & Desserts" },
      { key: "builder", label: "Nav: Pizza Builder" },
      { key: "reviews", label: "Nav: Reviews" },
      { key: "bookTable", label: "Nav: Book Table" },
      { key: "contact", label: "Nav: Contact" },
      { key: "basket", label: "Nav: Basket" },
      { key: "lightMode", label: "Light Mode Toggle" },
      { key: "darkMode", label: "Dark Mode Toggle" },
    ],
  },
  {
    id: "hero",
    title: "Hero Section",
    fields: [
      { key: "heroBadge", label: "Badge Text" },
      { key: "heroSubtitle", label: "Subtitle" },
      { key: "heroTitle", label: "Main Title" },
      { key: "heroDesc", label: "Description", long: LONG },
      { key: "heroDiscover", label: "Button: Discover Menu" },
      { key: "heroBook", label: "Button: Book a Table" },
    ],
  },
  {
    id: "menuSection",
    title: "Pizza Menu Section",
    fields: [
      { key: "menuPreTitle", label: "Pre-title" },
      { key: "menuTitle", label: "Title" },
      { key: "menuDesc", label: "Description", long: LONG },
      { key: "searchPlaceholder", label: "Search Placeholder" },
      { key: "allRecipes", label: "\"All Recipes\" Filter" },
      { key: "addToBasket", label: "Add to Basket Button" },
      { key: "each", label: "\"each\" (price suffix)" },
    ],
  },
  {
    id: "categories",
    title: "Pizza Categories",
    fields: [
      { key: "classic", label: "Classic" },
      { key: "specialty", label: "Specialty" },
      { key: "chicken", label: "Chicken" },
      { key: "meat", label: "Meat" },
      { key: "spicy", label: "Spicy" },
      { key: "vegetarian", label: "Vegetarian" },
    ],
  },
  {
    id: "builder",
    title: "Pizza Builder",
    fields: [
      { key: "builderPreTitle", label: "Pre-title" },
      { key: "builderTitle", label: "Title" },
      { key: "builderDesc", label: "Description", long: LONG },
      { key: "selectSize", label: "Step 1 Label" },
      { key: "layerToppings", label: "Step 2 Label" },
      { key: "customNameLabel", label: "Custom Name Field Label" },
      { key: "customNamePlaceholder", label: "Custom Name Placeholder" },
      { key: "totalComp", label: "Total Label" },
      { key: "commitToBasket", label: "Add to Basket Button" },
      { key: "baseDough", label: "Base Dough Label" },
      { key: "pizzaBase", label: "Pizza Base Name" },
      { key: "customPizzaDefaultName", label: "Default Custom Pizza Name" },
      { key: "noToppings", label: "No Toppings Message" },
      { key: "pricePredictor", label: "Price Predictor Title" },
      { key: "predictedValue", label: "Predicted Value Label" },
      { key: "customSavings", label: "Custom Savings Label" },
      {
        key: "customSavingsDesc",
        label: "Custom Savings Description",
        long: LONG,
      },
      { key: "closestMatch", label: "Closest Match Label" },
      { key: "similarity", label: "Similarity Label" },
      { key: "tasteProfile", label: "Flavor Profile Label" },
      { key: "predictForSizes", label: "Price Matrix Label" },
      { key: "saveSyp", label: "Savings Message ({amount} placeholder)" },
      { key: "animalProducts", label: "Animal Products Group Title" },
      { key: "vegetarianIngredients", label: "Vegetarian Group Title" },
      { key: "selectBasePizza", label: "Select Base Pizza Label" },
      { key: "baseIngredients", label: "Base Ingredients Label" },
      { key: "extraIngredientsTitle", label: "Extras Title" },
      { key: "extraIngredientsSubtitle", label: "Extras Subtitle" },
    ],
  },
  {
    id: "reservation",
    title: "Reservation Section",
    fields: [
      { key: "reservePreTitle", label: "Pre-title" },
      { key: "reserveTitle", label: "Title" },
      { key: "reserveDesc", label: "Description", long: LONG },
      { key: "fullName", label: "Full Name Field" },
      { key: "fullNamePlaceholder", label: "Full Name Placeholder" },
      { key: "emailAddress", label: "Email Field" },
      { key: "emailPlaceholder", label: "Email Placeholder" },
      { key: "guestNumber", label: "Guest Number Field" },
      { key: "selectGuests", label: "Select Guests Placeholder" },
      { key: "guestUnit", label: "Guest Unit Word" },
      { key: "arrivalDate", label: "Arrival Date Field" },
      { key: "selectDate", label: "Select Date Placeholder" },
      { key: "timeSlot", label: "Time Slot Field" },
      { key: "selectTime", label: "Select Time Placeholder" },
      { key: "dispatchReservation", label: "Submit Button" },
      { key: "reservationSecured", label: "Success Message" },
      { key: "valetWarning", label: "Valet Note", long: LONG },
    ],
  },
  {
    id: "reviews",
    title: "Reviews Section",
    fields: [
      { key: "reviewsPreTitle", label: "Pre-title" },
      { key: "reviewsTitle", label: "Title" },
      { key: "reviewsDesc", label: "Description", long: LONG },
      { key: "patronChronicles", label: "Reviews List Title" },
      { key: "expressOpinion", label: "Form Title" },
      { key: "gastronomyRating", label: "Rating Field Label" },
      { key: "patronName", label: "Name Field Label" },
      { key: "patronNamePlaceholder", label: "Name Placeholder" },
      { key: "criticComment", label: "Comment Field Label" },
      { key: "commentPlaceholder", label: "Comment Placeholder", long: LONG },
      { key: "dispatchReview", label: "Submit Button" },
      { key: "opinionCommitted", label: "Success Message" },
      { key: "noReviews", label: "Empty State Message" },
    ],
  },
  {
    id: "cart",
    title: "Basket & Checkout",
    fields: [
      { key: "yourBasket", label: "Basket Title" },
      { key: "orderCompleted", label: "Order Completed Message" },
      { key: "basketIsEmpty", label: "Empty Basket Title" },
      { key: "basketEmptyDesc", label: "Empty Basket Description" },
      { key: "browseMenu", label: "Browse Menu Button" },
      { key: "composition", label: "Composition Label" },
      { key: "remove", label: "Remove Button" },
      { key: "whatsappInitiated", label: "WhatsApp Initiated Message" },
      { key: "preparingInOven", label: "Preparing Message" },
      { key: "syriaReceipt", label: "Receipt Title" },
      { key: "subtotal", label: "Subtotal Label" },
      { key: "delivery", label: "Delivery Label" },
      { key: "free", label: "Free Label" },
      { key: "checkoutWhatsApp", label: "Checkout Button" },
      { key: "addMoreForFree", label: "Free Delivery Nudge ({diff} placeholder)" },
      { key: "placeAnother", label: "Place Another Order Button" },
      { key: "redirectWarning", label: "Redirect Notice", long: LONG },
    ],
  },
  {
    id: "sizes",
    title: "Sizes & Portions",
    fields: [
      { key: "small", label: "Small" },
      { key: "medium", label: "Medium" },
      { key: "large", label: "Large" },
      { key: "thin", label: "Thin" },
      { key: "standard", label: "Standard" },
      { key: "three_pcs", label: "3 Pieces" },
      { key: "six_pcs", label: "6 Pieces" },
    ],
  },
  {
    id: "sidesHeaders",
    title: "Sides & Desserts Section Headers",
    fields: [
      { key: "snacks", label: "Snacks Word" },
      { key: "desserts", label: "Desserts Word" },
      { key: "snacksPreTitle", label: "Snacks Pre-title" },
      { key: "snacksTitle", label: "Snacks Title" },
      { key: "snacksDesc", label: "Snacks Description", long: LONG },
      { key: "dessertsPreTitle", label: "Desserts Pre-title" },
      { key: "dessertsTitle", label: "Desserts Title" },
      { key: "dessertsDesc", label: "Desserts Description", long: LONG },
    ],
  },
  {
    id: "footer",
    title: "Footer",
    fields: [
      { key: "footerFeedback", label: "Feedback Line" },
      { key: "footerDesc", label: "About Text", long: LONG },
      { key: "footerCopyright", label: "Copyright Line" },
    ],
  },
];
