// Curated groups of page-text keys shown in the "Page Content" tab, mirroring
// the section comments in src/translations.js. Pizza names/descriptions and
// snack/dessert names/descriptions have their own dedicated editors (Pizzas
// and Extras tabs) so they aren't duplicated here. Every section title and
// field label is bilingual ({en, ar}) since this config drives the
// dashboard's own UI chrome, not site content.
const LONG = true;

export const CONTENT_SECTIONS = [
  {
    id: "navbar",
    title: { en: "Navbar & Menu Labels", ar: "شريط التنقل وقائمة الروابط" },
    fields: [
      { key: "home", label: { en: "Nav: Home", ar: "التنقل: الرئيسية" } },
      { key: "menu", label: { en: "Nav: Menu", ar: "التنقل: القائمة" } },
      { key: "extras", label: { en: "Nav: Sides & Desserts", ar: "التنقل: المقبلات والحلويات" } },
      { key: "builder", label: { en: "Nav: Pizza Builder", ar: "التنقل: صانع البيتزا" } },
      { key: "reviews", label: { en: "Nav: Reviews", ar: "التنقل: التقييمات" } },
      { key: "bookTable", label: { en: "Nav: Book Table", ar: "التنقل: حجز طاولة" } },
      { key: "contact", label: { en: "Nav: Contact", ar: "التنقل: تواصل معنا" } },
      { key: "basket", label: { en: "Nav: Basket", ar: "التنقل: السلة" } },
      { key: "lightMode", label: { en: "Light Mode Toggle", ar: "مبدّل الوضع الفاتح" } },
      { key: "darkMode", label: { en: "Dark Mode Toggle", ar: "مبدّل الوضع الداكن" } },
    ],
  },
  {
    id: "hero",
    title: { en: "Hero Section", ar: "قسم البداية" },
    fields: [
      { key: "heroBadge", label: { en: "Badge Text", ar: "نص الشارة" } },
      { key: "heroSubtitle", label: { en: "Subtitle", ar: "العنوان الفرعي" } },
      { key: "heroTitle", label: { en: "Main Title", ar: "العنوان الرئيسي" } },
      { key: "heroDesc", label: { en: "Description", ar: "الوصف" }, long: LONG },
      { key: "heroDiscover", label: { en: "Button: Discover Menu", ar: "زر: اكتشف القائمة" } },
      { key: "heroBook", label: { en: "Button: Book a Table", ar: "زر: احجز طاولة" } },
    ],
  },
  {
    id: "menuSection",
    title: { en: "Pizza Menu Section", ar: "قسم قائمة البيتزا" },
    fields: [
      { key: "menuPreTitle", label: { en: "Pre-title", ar: "العنوان التمهيدي" } },
      { key: "menuTitle", label: { en: "Title", ar: "العنوان" } },
      { key: "menuDesc", label: { en: "Description", ar: "الوصف" }, long: LONG },
      { key: "searchPlaceholder", label: { en: "Search Placeholder", ar: "نص حقل البحث" } },
      { key: "allRecipes", label: { en: '"All Recipes" Filter', ar: 'فلتر "كل الوصفات"' } },
      { key: "addToBasket", label: { en: "Add to Basket Button", ar: "زر أضف إلى السلة" } },
      { key: "each", label: { en: '"each" (price suffix)', ar: 'كلمة "للوحدة" (بعد السعر)' } },
    ],
  },
  {
    id: "categories",
    title: { en: "Pizza Categories", ar: "فئات البيتزا" },
    fields: [
      { key: "classic", label: { en: "Classic", ar: "كلاسيكية" } },
      { key: "specialty", label: { en: "Specialty", ar: "مميزة" } },
      { key: "chicken", label: { en: "Chicken", ar: "دجاج" } },
      { key: "meat", label: { en: "Meat", ar: "لحوم" } },
      { key: "spicy", label: { en: "Spicy", ar: "حارة" } },
      { key: "vegetarian", label: { en: "Vegetarian", ar: "نباتية" } },
    ],
  },
  {
    id: "builder",
    title: { en: "Pizza Builder", ar: "صانع البيتزا" },
    fields: [
      { key: "builderPreTitle", label: { en: "Pre-title", ar: "العنوان التمهيدي" } },
      { key: "builderTitle", label: { en: "Title", ar: "العنوان" } },
      { key: "builderDesc", label: { en: "Description", ar: "الوصف" }, long: LONG },
      { key: "selectSize", label: { en: "Step 1 Label", ar: "تسمية الخطوة ١" } },
      { key: "layerToppings", label: { en: "Step 2 Label", ar: "تسمية الخطوة ٢" } },
      { key: "customNameLabel", label: { en: "Custom Name Field Label", ar: "تسمية حقل الاسم المخصص" } },
      { key: "customNamePlaceholder", label: { en: "Custom Name Placeholder", ar: "نص حقل الاسم المخصص" } },
      { key: "totalComp", label: { en: "Total Label", ar: "تسمية الإجمالي" } },
      { key: "commitToBasket", label: { en: "Add to Basket Button", ar: "زر أضف إلى السلة" } },
      { key: "baseDough", label: { en: "Base Dough Label", ar: "تسمية العجينة الأساسية" } },
      { key: "pizzaBase", label: { en: "Pizza Base Name", ar: "اسم قاعدة البيتزا" } },
      { key: "customPizzaDefaultName", label: { en: "Default Custom Pizza Name", ar: "الاسم الافتراضي للبيتزا المخصصة" } },
      { key: "noToppings", label: { en: "No Toppings Message", ar: "رسالة عدم وجود إضافات" } },
      { key: "pricePredictor", label: { en: "Price Predictor Title", ar: "عنوان متنبئ السعر" } },
      { key: "predictedValue", label: { en: "Predicted Value Label", ar: "تسمية القيمة المتوقعة" } },
      { key: "customSavings", label: { en: "Custom Savings Label", ar: "تسمية التوفير المخصص" } },
      {
        key: "customSavingsDesc",
        label: { en: "Custom Savings Description", ar: "وصف التوفير المخصص" },
        long: LONG,
      },
      { key: "closestMatch", label: { en: "Closest Match Label", ar: "تسمية أقرب تطابق" } },
      { key: "similarity", label: { en: "Similarity Label", ar: "تسمية نسبة التشابه" } },
      { key: "tasteProfile", label: { en: "Flavor Profile Label", ar: "تسمية ملف النكهة" } },
      { key: "predictForSizes", label: { en: "Price Matrix Label", ar: "تسمية جدول الأسعار" } },
      { key: "saveSyp", label: { en: "Savings Message ({amount} placeholder)", ar: "رسالة التوفير (المتغير {amount})" } },
      { key: "animalProducts", label: { en: "Animal Products Group Title", ar: "عنوان مجموعة المنتجات الحيوانية" } },
      { key: "vegetarianIngredients", label: { en: "Vegetarian Group Title", ar: "عنوان مجموعة المكونات النباتية" } },
      { key: "selectBasePizza", label: { en: "Select Base Pizza Label", ar: "تسمية اختيار البيتزا الأساسية" } },
      { key: "baseIngredients", label: { en: "Base Ingredients Label", ar: "تسمية المكونات الأساسية" } },
      { key: "extraIngredientsTitle", label: { en: "Extras Title", ar: "عنوان الإضافات" } },
      { key: "extraIngredientsSubtitle", label: { en: "Extras Subtitle", ar: "العنوان الفرعي للإضافات" } },
    ],
  },
  {
    id: "reservation",
    title: { en: "Reservation Section", ar: "قسم الحجوزات" },
    fields: [
      { key: "reservePreTitle", label: { en: "Pre-title", ar: "العنوان التمهيدي" } },
      { key: "reserveTitle", label: { en: "Title", ar: "العنوان" } },
      { key: "reserveDesc", label: { en: "Description", ar: "الوصف" }, long: LONG },
      { key: "fullName", label: { en: "Full Name Field", ar: "حقل الاسم الكامل" } },
      { key: "fullNamePlaceholder", label: { en: "Full Name Placeholder", ar: "نص حقل الاسم الكامل" } },
      { key: "emailAddress", label: { en: "Email Field", ar: "حقل البريد الإلكتروني" } },
      { key: "emailPlaceholder", label: { en: "Email Placeholder", ar: "نص حقل البريد الإلكتروني" } },
      { key: "guestNumber", label: { en: "Guest Number Field", ar: "حقل عدد الضيوف" } },
      { key: "selectGuests", label: { en: "Select Guests Placeholder", ar: "نص اختيار عدد الضيوف" } },
      { key: "guestUnit", label: { en: "Guest Unit Word", ar: "كلمة وحدة الضيوف" } },
      { key: "arrivalDate", label: { en: "Arrival Date Field", ar: "حقل تاريخ الوصول" } },
      { key: "selectDate", label: { en: "Select Date Placeholder", ar: "نص اختيار التاريخ" } },
      { key: "timeSlot", label: { en: "Time Slot Field", ar: "حقل الفترة الزمنية" } },
      { key: "selectTime", label: { en: "Select Time Placeholder", ar: "نص اختيار الوقت" } },
      { key: "dispatchReservation", label: { en: "Submit Button", ar: "زر الإرسال" } },
      { key: "reservationSecured", label: { en: "Success Message", ar: "رسالة النجاح" } },
      { key: "valetWarning", label: { en: "Valet Note", ar: "ملاحظة خدمة صف السيارات" }, long: LONG },
    ],
  },
  {
    id: "reviews",
    title: { en: "Reviews Section", ar: "قسم التقييمات" },
    fields: [
      { key: "reviewsPreTitle", label: { en: "Pre-title", ar: "العنوان التمهيدي" } },
      { key: "reviewsTitle", label: { en: "Title", ar: "العنوان" } },
      { key: "reviewsDesc", label: { en: "Description", ar: "الوصف" }, long: LONG },
      { key: "patronChronicles", label: { en: "Reviews List Title", ar: "عنوان قائمة التقييمات" } },
      { key: "expressOpinion", label: { en: "Form Title", ar: "عنوان النموذج" } },
      { key: "gastronomyRating", label: { en: "Rating Field Label", ar: "تسمية حقل التقييم" } },
      { key: "patronName", label: { en: "Name Field Label", ar: "تسمية حقل الاسم" } },
      { key: "patronNamePlaceholder", label: { en: "Name Placeholder", ar: "نص حقل الاسم" } },
      { key: "criticComment", label: { en: "Comment Field Label", ar: "تسمية حقل التعليق" } },
      { key: "commentPlaceholder", label: { en: "Comment Placeholder", ar: "نص حقل التعليق" }, long: LONG },
      { key: "dispatchReview", label: { en: "Submit Button", ar: "زر الإرسال" } },
      { key: "opinionCommitted", label: { en: "Success Message", ar: "رسالة النجاح" } },
      { key: "noReviews", label: { en: "Empty State Message", ar: "رسالة عدم وجود تقييمات" } },
    ],
  },
  {
    id: "cart",
    title: { en: "Basket & Checkout", ar: "السلة والدفع" },
    fields: [
      { key: "yourBasket", label: { en: "Basket Title", ar: "عنوان السلة" } },
      { key: "orderCompleted", label: { en: "Order Completed Message", ar: "رسالة اكتمال الطلب" } },
      { key: "basketIsEmpty", label: { en: "Empty Basket Title", ar: "عنوان السلة الفارغة" } },
      { key: "basketEmptyDesc", label: { en: "Empty Basket Description", ar: "وصف السلة الفارغة" } },
      { key: "browseMenu", label: { en: "Browse Menu Button", ar: "زر تصفح القائمة" } },
      { key: "composition", label: { en: "Composition Label", ar: "تسمية المكونات" } },
      { key: "remove", label: { en: "Remove Button", ar: "زر الحذف" } },
      { key: "whatsappInitiated", label: { en: "WhatsApp Initiated Message", ar: "رسالة بدء الواتساب" } },
      { key: "preparingInOven", label: { en: "Preparing Message", ar: "رسالة التحضير" } },
      { key: "syriaReceipt", label: { en: "Receipt Title", ar: "عنوان الفاتورة" } },
      { key: "subtotal", label: { en: "Subtotal Label", ar: "تسمية المجموع الفرعي" } },
      { key: "delivery", label: { en: "Delivery Label", ar: "تسمية التوصيل" } },
      { key: "free", label: { en: "Free Label", ar: "تسمية مجاني" } },
      { key: "checkoutWhatsApp", label: { en: "Checkout Button", ar: "زر إتمام الطلب" } },
      { key: "addMoreForFree", label: { en: "Free Delivery Nudge ({diff} placeholder)", ar: "تنبيه التوصيل المجاني (المتغير {diff})" } },
      { key: "placeAnother", label: { en: "Place Another Order Button", ar: "زر طلب جديد" } },
      { key: "redirectWarning", label: { en: "Redirect Notice", ar: "إشعار إعادة التوجيه" }, long: LONG },
    ],
  },
  {
    id: "sizes",
    title: { en: "Sizes & Portions", ar: "الأحجام والوجبات" },
    fields: [
      { key: "small", label: { en: "Small", ar: "صغير" } },
      { key: "medium", label: { en: "Medium", ar: "وسط" } },
      { key: "large", label: { en: "Large", ar: "كبير" } },
      { key: "thin", label: { en: "Thin", ar: "رقيقة" } },
      { key: "standard", label: { en: "Standard", ar: "عادي" } },
      { key: "three_pcs", label: { en: "3 Pieces", ar: "٣ قطع" } },
      { key: "six_pcs", label: { en: "6 Pieces", ar: "٦ قطع" } },
    ],
  },
  {
    id: "sidesHeaders",
    title: { en: "Sides & Desserts Section Headers", ar: "عناوين قسم المقبلات والحلويات" },
    fields: [
      { key: "snacks", label: { en: "Snacks Word", ar: "كلمة الوجبات الخفيفة" } },
      { key: "desserts", label: { en: "Desserts Word", ar: "كلمة الحلويات" } },
      { key: "snacksPreTitle", label: { en: "Snacks Pre-title", ar: "العنوان التمهيدي للوجبات الخفيفة" } },
      { key: "snacksTitle", label: { en: "Snacks Title", ar: "عنوان الوجبات الخفيفة" } },
      { key: "snacksDesc", label: { en: "Snacks Description", ar: "وصف الوجبات الخفيفة" }, long: LONG },
      { key: "dessertsPreTitle", label: { en: "Desserts Pre-title", ar: "العنوان التمهيدي للحلويات" } },
      { key: "dessertsTitle", label: { en: "Desserts Title", ar: "عنوان الحلويات" } },
      { key: "dessertsDesc", label: { en: "Desserts Description", ar: "وصف الحلويات" }, long: LONG },
      { key: "sauces", label: { en: "Sauces Word", ar: "كلمة الصلصات" } },
      { key: "drinks", label: { en: "Drinks Word", ar: "كلمة المشروبات" } },
      { key: "saucesPreTitle", label: { en: "Sauces Pre-title", ar: "العنوان التمهيدي للصلصات" } },
      { key: "saucesTitle", label: { en: "Sauces Title", ar: "عنوان الصلصات" } },
      { key: "saucesDesc", label: { en: "Sauces Description", ar: "وصف الصلصات" }, long: LONG },
      { key: "drinksPreTitle", label: { en: "Drinks Pre-title", ar: "العنوان التمهيدي للمشروبات" } },
      { key: "drinksTitle", label: { en: "Drinks Title", ar: "عنوان المشروبات" } },
      { key: "drinksDesc", label: { en: "Drinks Description", ar: "وصف المشروبات" }, long: LONG },
    ],
  },
  {
    id: "footer",
    title: { en: "Footer", ar: "الفوتر" },
    fields: [
      { key: "footerFeedback", label: { en: "Feedback Line", ar: "سطر طلب الملاحظات" } },
      { key: "footerDesc", label: { en: "About Text", ar: "نص عن المطعم" }, long: LONG },
      { key: "footerCopyright", label: { en: "Copyright Line", ar: "سطر حقوق النشر" } },
    ],
  },
];
