import heroImage from "./assets/images/bistro_hero_1783274357884.jpg";
import margheritaImage from "./assets/images/margherita_pizza_1783274371968.jpg";
import burrataImage from "./assets/images/burrata_pizza_1783274387992.jpg";
import footerBgImage from "./assets/images/footer_ingredients_1783274399702.jpg";

// High quality pizza and ambient illustrations
export const IMAGES = {
  hero: heroImage,
  margherita: margheritaImage,
  burrata: burrataImage,
  footerBg: footerBgImage,
};

export const INITIAL_MENU = [
  {
    id: "pizza-1",
    number: 1,
    name: "The Classic Margherita",
    description: "Sauce, Cheese",
    ingredients: ["Sauce", "Cheese"],
    category: "classic",
    prices: { small: 450, medium: 900, large: 1400, thin: 1200 },
    image: IMAGES.margherita,
  },
  {
    id: "pizza-2",
    number: 2,
    name: "The Salami One",
    description: "Sauce, Cheese, Beef salami, Mushroom",
    ingredients: ["Sauce", "Cheese", "Ham", "Mushroom"],
    category: "classic",
    prices: { small: 500, medium: 1050, large: 1600, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-3",
    number: 3,
    name: "My Dream",
    description: "Sauce, Minced Beef, Cheese, pepper",
    ingredients: ["Sauce", "Minced meat", "Cheese", "Red pepper"],
    category: "specialty",
    prices: { small: 500, medium: 1050, large: 1600, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-4",
    number: 4,
    name: "Pizzabaker Special",
    description: "Sauce, Minced Beef, Onion, Cheese, Bacon cut",
    ingredients: ["Sauce", "Minced meat", "Onion", "Cheese", "Baconcut"],
    category: "specialty",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-5",
    number: 5,
    name: "Hawaii",
    description: "Sauce, Minced Beef, Onion, Cheese, Pineapple",
    ingredients: ["Sauce", "Minced meat", "Onion", "Cheese", "Pineapple"],
    category: "specialty",
    prices: { small: 500, medium: 1050, large: 1600, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-6",
    number: 6,
    name: "Pepperoni",
    description: "Sauce, Onion, Cheese, Pepperoni, pepper",
    ingredients: ["Sauce", "Onion", "Cheese", "Pepperoni", "Red pepper"],
    category: "meat",
    prices: { small: 500, medium: 1050, large: 1600, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-7",
    number: 7,
    name: "Mexicano",
    description:
      "Sauce, Garlic, Nacho chips, Chili, Marinated beef, Chicken, Corn",
    ingredients: [
      "Sauce",
      "Garlic",
      "Nacho chips",
      "Cheese",
      "Chili",
      "Marinated beef",
      "Chicken",
      "Corn",
    ],
    category: "spicy",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-8",
    number: 8,
    name: "Meat Lover",
    description: "Sauce, Garlic, Cheese, Bacon cut, Marinated beef",
    ingredients: ["Sauce", "Garlic", "Cheese", "Baconcut", "Marinated beef"],
    category: "meat",
    prices: { small: 500, medium: 1050, large: 1600, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-9",
    number: 9,
    name: "The Marinated One",
    description: "Sauce, Onion, Cheese, Mushroom, Marinated beef",
    ingredients: ["Sauce", "Onion", "Cheese", "Mushroom", "Marinated beef"],
    category: "meat",
    prices: { small: 500, medium: 1050, large: 1600, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-10",
    number: 10,
    name: "Hot Pepper Beef",
    description: "Sauce, Onion, Cheese, Mushroom, pepper, Pepper beef",
    ingredients: [
      "Sauce",
      "Onion",
      "Cheese",
      "Mushroom",
      "Red pepper",
      "Pepper beef",
    ],
    category: "spicy",
    prices: { small: 500, medium: 1050, large: 1600, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-11",
    number: 11,
    name: "The Flame",
    description:
      "Taco sauce, Minced meat, Taco spice, Nacho chips, Cheese, Jalapeño",
    ingredients: [
      "Tacosauce",
      "Minced meat",
      "Seasoning mix",
      "Nacho chips",
      "Cheese",
      "Jalapeño",
    ],
    category: "spicy",
    prices: { small: 500, medium: 1050, large: 1600, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-12",
    number: 12,
    name: "Taco Chicken",
    description:
      "Taco sauce, Taco spice, Nacho chips, Cheese, Jalapeño, Marinated chicken",
    ingredients: [
      "Tacosauce",
      "Seasoning mix",
      "Nacho chips",
      "Cheese",
      "Jalapeño",
      "Marinated chicken",
    ],
    category: "spicy",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-13",
    number: 13,
    name: "Master Chicken",
    description: "Sauce, Onion, Cheese, Mushroom, Corn, Chicken",
    ingredients: ["Sauce", "Onion", "Cheese", "Mushroom", "Corn", "Chicken"],
    category: "chicken",
    prices: { small: 500, medium: 1050, large: 1600, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-14",
    number: 14,
    name: "Master Favourite",
    description: "Sauce, Minced Beef, Cheese, Pineapple, Luxury Beef bacon",
    ingredients: [
      "Sauce",
      "Minced meat",
      "Cheese",
      "Pineapple",
      "Luxury bacon",
    ],
    category: "specialty",
    prices: { small: 500, medium: 1050, large: 1600, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-15",
    number: 15,
    name: "Spark Baker",
    description: "Sauce, Minced Meat, Onion, Garlic, Cheese and Jalapeños",
    ingredients: [
      "Sauce",
      "Minced meat",
      "Onion",
      "Garlic",
      "Cheese",
      "Jalapeño",
    ],
    category: "spicy",
    prices: { small: 500, medium: 1050, large: 1600, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-16",
    number: 16,
    name: "Chicken Deluxe",
    description: "Sauce, Onion, Cheese, pepper, Chicken, Luxury Beef bacon",
    ingredients: [
      "Sauce",
      "Onion",
      "Cheese",
      "Red pepper",
      "Chicken",
      "Luxury bacon",
    ],
    category: "chicken",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-17",
    number: 17,
    name: "Chicken Pesto",
    description: "Sauce, Tomato, Chili, Marinated Chicken, Pesto",
    ingredients: [
      "Sauce",
      "Tomato",
      "Cheese",
      "Chili",
      "Marinated chicken",
      "Pesto",
    ],
    category: "chicken",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-18",
    number: 18,
    name: "Vegan",
    description: "Sauce, Onion, Cheese, pepper, Corn, Mushroom, Pineapple",
    ingredients: [
      "Sauce",
      "Onion",
      "Cheese",
      "Red pepper",
      "Corn",
      "Mushroom",
      "Pineapple",
    ],
    category: "vegetarian",
    prices: { small: 500, medium: 950, large: 1450, thin: 900 },
    image: IMAGES.burrata,
  },
  {
    id: "pizza-19",
    number: 19,
    name: "Pizza Kebab",
    description: "Taco sauce, Cheese, Kebab beef, Corn, Jalapeño, Red onion",
    ingredients: [
      "Tacosauce",
      "Cheese",
      "Kebab meat",
      "Corn",
      "Jalapeño",
      "Red onion",
      "Kebab dressing",
    ],
    category: "specialty",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-20",
    number: 20,
    name: "Mr. Mix",
    description: "Sauce, Cheese, Beef salami, Beef bacon cut",
    ingredients: ["Sauce", "Cheese", "Ham", "Baconcut"],
    category: "meat",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-21",
    number: 21,
    name: "Mr. X",
    description: "Sauce, Minced Beef, Onion, Cheese, Pepperoni, Pineapple",
    ingredients: [
      "Sauce",
      "Minced meat",
      "Onion",
      "Cheese",
      "Pepperoni",
      "Pineapple",
    ],
    category: "specialty",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-22",
    number: 22,
    name: "The Double Decker",
    description: "Sauce, Minced Beef, Beef salami, Cheese, Oregano",
    ingredients: ["Sauce", "Minced meat", "Cheese", "Ham", "Oregano"],
    category: "meat",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-23",
    number: 23,
    name: "Chorizo Special",
    description: "Sauce, Chorizo, Onion, Cheese, Minced Beef",
    ingredients: ["Sauce", "Chorizo", "Onion", "Cheese", "Marinated beef"],
    category: "meat",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-24",
    number: 24,
    name: "Chicken Hot",
    description: "Sauce, Cheese, Beef Bacon, Pineapple, Hot chicken",
    ingredients: ["Sauce", "Cheese", "Hot chicken", "Bacon", "Pineapple"],
    category: "chicken",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-25",
    number: 25,
    name: "Chorizo",
    description: "Sauce, Tomato, Chorizo, Pesto, Oregano",
    ingredients: ["Sauce", "Tomatoes", "Cheese", "Chorizo", "Pesto", "Oregano"],
    category: "meat",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-26",
    number: 26,
    name: "Four Seasons",
    description:
      "Sauce, Cheese, mushroom pepper, onion, corn, olives, Feferoni, Fresh Tomato Slices, Jalapeño, oregano",
    ingredients: [
      "Sauce",
      "Onion",
      "Cheese",
      "Red pepper",
      "Corn",
      "Mushroom",
      "Pineapple",
      "Tomato",
      "Oregano",
    ],
    category: "vegetarian",
    prices: { small: 500, medium: 1000, large: 1550, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-27",
    number: 27,
    name: "Tuna Moby",
    description: "Sauce, Cheese, Tuna, Feta cheese, Onion",
    ingredients: ["Sauce", "Onion", "Cheese", "Feta cheese"],
    category: "vegetarian",
    prices: { small: 500, medium: 1050, large: 1600, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-28",
    number: 28,
    name: "Greek Special",
    description: "Sauce, Cheese, Feta cheese, Pepper, Feferoni, olives",
    ingredients: [
      "Sauce",
      "Cheese",
      "Squash",
      "Chili",
      "Feta cheese",
      "Red onion",
    ],
    category: "vegetarian",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-29",
    number: 29,
    name: "Tropicana",
    description: "Sauce, Cheese, Chicken, Banana, Pineapple, Curry Spice",
    ingredients: ["Sauce", "Cheese", "Chicken", "Pineapple"],
    category: "specialty",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "pizza-30",
    number: 30,
    name: "BBQ",
    description: "Sauce, Cheese, Red onion, Corn, Minced Beef",
    ingredients: ["Sauce", "Cheese", "Pork", "Baconcut", "Corn", "Red onion"],
    category: "meat",
    prices: { small: 600, medium: 1100, large: 1650, thin: 900 },
    image:
      "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&q=80&w=600",
  },
];

export const INITIAL_REVIEWS = [
  {
    id: "rev-1",
    name: "Abdullah Alhamwi",
    rating: 5,
    comment: "review1_comment",
    date: "July 2, 2026",
  },
  {
    id: "rev-2",
    name: "Saral Aljani",
    rating: 5,
    comment: "review2_comment",
    date: "June 28, 2026",
  },
  {
    id: "rev-3",
    name: "Haitham Jlailati",
    rating: 5,
    comment: "review3_comment",
    date: "June 15, 2026",
  },
];

export const CUSTOM_TOPPINGS = [
  { id: "topping-cheese", name: "Cheese", price: 60, icon: "🧀" },
  { id: "topping-ham", name: "Ham", price: 80, icon: "🍖" },
  { id: "topping-mush", name: "Mushroom", price: 50, icon: "🍄" },
  { id: "topping-minced", name: "Minced meat", price: 90, icon: "🥩" },
  { id: "topping-pepper", name: "Red pepper", price: 40, icon: "🫑" },
  { id: "topping-onion", name: "Onion", price: 40, icon: "🧅" },
  { id: "topping-baconcut", name: "Baconcut", price: 90, icon: "🥓" },
  { id: "topping-pineapple", name: "Pineapple", price: 60, icon: "🍍" },
  { id: "topping-pep", name: "Pepperoni", price: 85, icon: "🍕" },
  { id: "topping-garlic", name: "Garlic", price: 30, icon: "🧄" },
  { id: "topping-nacho", name: "Nacho chips", price: 50, icon: "🌮" },
  { id: "topping-chili", name: "Chili", price: 40, icon: "🌶️" },
  {
    id: "topping-marinated-beef",
    name: "Marinated beef",
    price: 100,
    icon: "🥩",
  },
  { id: "topping-chicken", name: "Chicken", price: 90, icon: "🍗" },
  { id: "topping-corn", name: "Corn", price: 40, icon: "🌽" },
  { id: "topping-pepper-beef", name: "Pepper beef", price: 100, icon: "🥩" },
  { id: "topping-jalapeno", name: "Jalapeño", price: 45, icon: "🌶️" },
  {
    id: "topping-marinated-chicken",
    name: "Marinated chicken",
    price: 95,
    icon: "🍗",
  },
  { id: "topping-luxury-bacon", name: "Luxury bacon", price: 110, icon: "🥓" },
  { id: "topping-tomato", name: "Tomato", price: 45, icon: "🍅" },
  { id: "topping-pesto", name: "Pesto", price: 50, icon: "🟢" },
  { id: "topping-kebab", name: "Kebab meat", price: 105, icon: "🥩" },
  { id: "topping-red-onion", name: "Red onion", price: 40, icon: "🧅" },
  { id: "topping-oregano", name: "Oregano", price: 20, icon: "🌿" },
  { id: "topping-chorizo", name: "Chorizo", price: 95, icon: "🌭" },
  { id: "topping-hot-chicken", name: "Hot chicken", price: 95, icon: "🍗" },
  { id: "topping-squash", name: "Squash", price: 50, icon: "🥒" },
  { id: "topping-feta", name: "Feta cheese", price: 75, icon: "🥛" },
  { id: "topping-pork", name: "Pork", price: 90, icon: "🥩" },
];

export const EXTRAS_MENU = {
  snacks: [
    {
      id: "snack-31",
      number: 31,
      name: "Garlic Bread",
      arabicName: "خبزة الثوم",
      translationKey: "garlic_bread",
      prices: { small: 350, large: 700 },
      sizes: ["small", "large"],
      localImageNames: [
        "garlic_bread.jpeg",
        "garlic_bread.jpg",
        "garlic_bread.png",
        "1.jpeg",
        "1.png",
        "garlic.jpeg",
      ],
      image: "public/snacks/garlic_bread.png",
    },
    {
      id: "snack-32",
      number: 32,
      name: "Chicken Drumsticks",
      arabicName: "دبابيس دجاج",
      translationKey: "chicken_drumsticks",
      prices: { three_pcs: 400, six_pcs: 700 },
      sizes: ["three_pcs", "six_pcs"],
      localImageNames: [
        "chicken_drumsticks.jpeg",
        "chicken_drumsticks.jpg",
        "chicken_drumsticks.png",
        "2.jpeg",
        "2.png",
        "drumsticks.jpeg",
      ],
      image: "public/snacks/chicken_drumsticks.png",
    },
  ],
  desserts: [
    {
      id: "dessert-33",
      number: 33,
      name: "Nutella Pure",
      arabicName: "نوتيلا بيور",
      translationKey: "pure_nutella",
      prices: { standard: 500 },
      localImageNames: [
        "nutella_pure.jpeg",
        "nutella_pure.jpg",
        "nutella_pure.png",
        "1.jpeg",
        "1.png",
        "pure_nutella.jpeg",
      ],
      image: "public/dessert/nutella_pure.png",
    },
    {
      id: "dessert-34",
      number: 34,
      name: "Nutella Pistachio",
      arabicName: "نوتيلا بستاشيو",
      translationKey: "nutella_pistachio",
      prices: { standard: 600 },
      localImageNames: [
        "nutella_pistachio.jpeg",
        "nutella_pistachio.jpg",
        "nutella_pistachio.png",
        "2.jpeg",
        "2.png",
        "pistachio.jpeg",
      ],
      image: "public/dessert/nutella_pistachio.png",
    },
    {
      id: "dessert-35",
      number: 35,
      name: "Nutella with Banana",
      arabicName: "نوتيلا بالموز",
      translationKey: "nutella_banana",
      prices: { standard: 600 },
      localImageNames: [
        "nutella_banana.jpeg",
        "nutella_banana.jpg",
        "nutella_banana.png",
        "3.jpeg",
        "3.png",
        "banana.jpeg",
      ],
      image: "public/dessert/nutella_banana.png",
    },
    {
      id: "dessert-36",
      number: 36,
      name: "Nutella with Strawberry",
      arabicName: "نوتيلا بالفريز",
      translationKey: "nutella_strawberry",
      prices: { standard: 600 },
      localImageNames: [
        "nutella_strawberry.jpeg",
        "nutella_strawberry.jpg",
        "nutella_strawberry.png",
        "4.jpeg",
        "4.png",
        "strawberry.jpeg",
      ],
      image: "public/dessert/nutella_strawberry.png",
    },
    {
      id: "dessert-37",
      number: 37,
      name: "Fruity Nutella",
      arabicName: "نوتيلا فواكه",
      translationKey: "fruity_nutella",
      prices: { standard: 700 },
      localImageNames: [
        "fruity_nutella.jpeg",
        "fruity_nutella.jpg",
        "fruity_nutella.png",
        "5.jpeg",
        "5.png",
        "fruity.jpeg",
      ],
      image: "	public/dessert/fruity_nutella.png",
    },
    {
      id: "dessert-38",
      number: 38,
      name: "Fruity Pistachio Nutella",
      arabicName: "نوتيلا بستاشيو فواكه",
      translationKey: "fruity_pistachio_nutella",
      prices: { standard: 750 },
      localImageNames: [
        "fruity_pistachio_nutella.jpeg",
        "fruity_pistachio_nutella.jpg",
        "fruity_pistachio_nutella.png",
        "6.jpeg",
        "6.png",
        "fruity_pistachio.jpeg",
      ],
      image: "public/dessert/fruity_pistachio_nutella.png",
    },
  ],
};
